sudo: required
services:
  - docker

before_install:
  - docker build -t jbevans451212/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jbevans451212/react-test npm test -- --coverage

after_success:
  - docker build -t  jbevans451212/multi-client ./client
  - docker build -t  jbevans451212/multi-nginx ./nginx
  - docker build -t  jbevans451212/multi-server ./server
  - docker build -t  jbevans451212/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker  login -u "$DOCKER_ID" --password-stdin
  #take  iages and  push to docker hub
  - docker push jbevans451212/multi-client
  - docker push jbevans451212/multi-nginx
  - docker push jbevans451212/multi-server
  - docker push jbevans451212/multi-worker


